#pragma once
#include <SDKDDKVer.h>

#include <stdio.h>
#include <cmath>
#include <iostream>
#include <algorithm>
#include <cstdlib>
#include <math.h>
#include <vector>
#include <queue>
#include <stack>
#include <deque>
#include <set>
#include <sstream>
#include <iomanip>
#include <conio.h>
#include <tchar.h>
#include <utility>
#include <map>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_mixer.h>
#include <SDL_ttf.h>